services:
  - type: web
    name: Assurant
    env: python
    pythonVersion: "3.11.4"  # Adicione esta linha
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --timeout 120 --workers 1
    autoDeploy: true
    envVars:
      - key: PYTHON_VERSION
        value: 3.11